server:
  port: 8264

shiroMd5Count: 9841

myJdbc:
  basePackage: blog.db.dao
  daoSuffix: Dao
  sqlLoader: /sql
  url: jdbc:mysql://123.206.183.163:3306/article
  userName: root
  passWord: 245167215
spring:
  mail:
    host: smtp.163.com
    username: m18390588753@163.com
    password: 2507483326li
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

