myJdbc:
  basePackage: blog.db.dao
  daoSuffix: Dao
  sqlLoader: /sql
  url: jdbc:mysql://localhost/article
  userName: root
  passWord: 123456
spring:
  mail:
    host: smtp.163.com
    username: m18390588753@163.com
    password: 2507483326li
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

